language:
  elixir
otp_release:
  - 17.4

# TODO: Temporary workaround until Elixir v1.1 is out
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.1.0-beta/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

sudo:
  false
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - andrea@leopardi.me
